#!/usr/bin/env bash
# Charger-aware battery charge policy for the GA403WM.
#
# Why this exists: the 2025 G14 dropped USB-C passthrough charging that
# the 2024 model had. The barrel charger does battery bypass; USB-C does
# not. So you want to cap at ~80% on USB-C / battery for longevity, but
# allow a full 100% top-off when the barrel charger is plugged in.
#
# Args:
#   $1 (optional) USBC_LIMIT   — cap on USB-C / battery   (default 80)
#   $2 (optional) BARREL_LIMIT — cap on barrel charger    (default 100)
#
# Examples:
#   bash install-battery-limit.sh           # 80 on USB-C, 100 on barrel
#   bash install-battery-limit.sh 70        # 70 on USB-C, 100 on barrel
#   bash install-battery-limit.sh 80 80     # static 80% (no boost on barrel)
#   bash install-battery-limit.sh 100 100   # effectively disable the cap
#
# Components installed:
#   /usr/local/bin/battery-charge-policy   — re-evaluates the threshold
#   /etc/udev/rules.d/90-battery.rules     — runs the script on charger events
set -euo pipefail

USBC_LIMIT="${1:-80}"
BARREL_LIMIT="${2:-100}"

for v in "$USBC_LIMIT" "$BARREL_LIMIT"; do
    if ! [[ "$v" =~ ^[0-9]+$ ]] || [ "$v" -lt 1 ] || [ "$v" -gt 100 ]; then
        echo "Invalid limit: $v (must be an integer 1..100)" >&2
        exit 1
    fi
done

if [ ! -e /sys/class/power_supply/BAT1/charge_control_end_threshold ]; then
    echo "BAT1 not found. This script targets the G14 GA403WM." >&2
    echo "Check 'ls /sys/class/power_supply/' and edit the script if your battery is BAT0." >&2
    exit 1
fi

sudo tee /usr/local/bin/battery-charge-policy >/dev/null <<EOF
#!/usr/bin/env bash
# Battery charge policy — auto-generated by install-battery-limit.sh.
# Re-run the installer with new args to change the limits.
set -e

THRESHOLD_FILE=/sys/class/power_supply/BAT1/charge_control_end_threshold
[ -w "\$THRESHOLD_FILE" ] || exit 0

ACAD_ONLINE=0
[ -r /sys/class/power_supply/ACAD/online ] \\
    && ACAD_ONLINE=\$(cat /sys/class/power_supply/ACAD/online)

if [ "\$ACAD_ONLINE" = "1" ]; then
    echo ${BARREL_LIMIT} > "\$THRESHOLD_FILE"
    logger -t battery-charge-policy "barrel charger online -> ${BARREL_LIMIT}%"
else
    echo ${USBC_LIMIT} > "\$THRESHOLD_FILE"
    logger -t battery-charge-policy "USB-C or battery -> ${USBC_LIMIT}%"
fi
EOF
sudo chmod 0755 /usr/local/bin/battery-charge-policy

sudo tee /etc/udev/rules.d/90-battery.rules >/dev/null <<'EOF'
# Charger-aware battery charge policy.
# - On any power_supply add: re-evaluate (covers boot enumeration order)
# - On Mains / USB charger state changes: re-evaluate
# We deliberately do NOT match change events on Battery devices because
# BAT1 emits a change event on every capacity tick.
ACTION=="add", SUBSYSTEM=="power_supply", RUN+="/usr/local/bin/battery-charge-policy"
ACTION=="change", SUBSYSTEM=="power_supply", ATTR{type}=="Mains", RUN+="/usr/local/bin/battery-charge-policy"
ACTION=="change", SUBSYSTEM=="power_supply", ATTR{type}=="USB", RUN+="/usr/local/bin/battery-charge-policy"
EOF

sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=power_supply --action=change

sleep 1
echo
echo "Charger-aware battery policy installed:"
echo "  Barrel charger online  -> ${BARREL_LIMIT}%"
echo "  USB-C only or battery  -> ${USBC_LIMIT}%"
echo
echo "Current state:"
echo "  ACAD online:    $(cat /sys/class/power_supply/ACAD/online)"
echo "  Charge limit:   $(cat /sys/class/power_supply/BAT1/charge_control_end_threshold)%"
echo
echo "Plug or unplug the barrel charger and the threshold should flip"
echo "between ${USBC_LIMIT} and ${BARREL_LIMIT} within a second."
echo
echo "Logs: journalctl -t battery-charge-policy"
echo
echo "To temporarily override the current threshold (resets on next charger event):"
echo "  echo 100 | sudo tee /sys/class/power_supply/BAT1/charge_control_end_threshold"
